FROM fluent/fluent-bit:v1.11-debian

USER root
WORKDIR /home/fluent
ENV PATH /fluent-bit/vendor/bundle/ruby/2.6.0/bin:$PATH
ENV GEM_PATH /fluent-bit/vendor/bundle/ruby/2.6.0
ENV GEM_HOME /fluent-bit/vendor/bundle/ruby/2.6.0

# skip runtime bundler installation
ENV fluent-bit_DISABLE_BUNDLER_INJECTION 1

COPY Gemfile* /fluent-bit/
RUN sed -i 's|deb.debian.org/debian|archive.debian.org/debian|g' /etc/apt/sources.list && \
    sed -i 's|security.debian.org/debian-security|archive.debian.org/debian-security|g' /etc/apt/sources.list && \
    sed -i '/stretch-updates/d' /etc/apt/sources.list && \
    apt-get -o Acquire::Check-Valid-Until=false update
RUN buildDeps="sudo make gcc g++ libc-dev libffi-dev" \
  runtimeDeps="" \
      && apt-get update \
     && apt-get upgrade -y \
     && apt-get install \
     -y --no-install-recommends \
     $buildDeps $runtimeDeps net-tools \
    && gem install bundler --version 2.1.4 \
    && bundle config silence_root_warning true \
    && bundle install --gemfile=/fluent-bit/Gemfile --path=/fluent-bit/vendor/bundle \
    && SUDO_FORCE_REMOVE=yes \
    apt-get purge -y --auto-remove \
                  -o APT::AutoRemove::RecommendsImportant=false \
                  $buildDeps \
 && rm -rf /var/lib/apt/lists/* \
    && gem sources --clear-all \
    && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

RUN touch /fluent-bit/etc/disable.conf
RUN gem install fluent-plugin-grafana-loki -v 1.2.18
# Copy plugins
COPY plugins /fluent-bit/plugins/
COPY entrypoint.sh /fluent-bit/entrypoint.sh
# chmod needed in full Linux env :)
RUN chmod 755 /fluent-bit/entrypoint.sh

# Environment variables
ENV fluent-bit_OPT=""
ENV fluent-bit_CONF="fluent.conf"

# Overwrite ENTRYPOINT to run fluent-bit as root for /var/log / /var/lib
ENTRYPOINT ["tini", "--", "/fluent-bit/entrypoint.sh"]
